version: '3.8'

services:
  record-service:
    build:
      context: .
      dockerfile: record-service/Dockerfile
    container_name: record_service_api
    env_file:
      - .env
    volumes:
      - ./record-service/src:/app/record-service/src
      - ./shared/src:/app/shared/src
      - ./local_data/output:/app/data/output
    ports:
      - "8000:8000"
    command: ["uvicorn", "record-service.src.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app"]
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-True}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - SALESFORCE_CLIENT_ID=${SALESFORCE_CLIENT_ID}
      - SALESFORCE_CLIENT_SECRET=${SALESFORCE_CLIENT_SECRET}
      - SALESFORCE_USERNAME=${SALESFORCE_USERNAME}
      - SALESFORCE_PASSWORD=${SALESFORCE_PASSWORD}
      - SALESFORCE_TOKEN_URL=${SALESFORCE_TOKEN_URL}
      - DATA_PATH_OUTPUT=/app/data/output

  bulk-service:
    build:
      context: .
      dockerfile: bulk-service/Dockerfile
    container_name: bulk_service_api
    env_file:
      - .env
    volumes:
      - ./bulk-service/src:/app/bulk-service/src
      - ./shared/src:/app/shared/src
      - ./local_data/input:/app/data/input
      - ./local_data/output:/app/data/output
      - ./local_data/failed:/app/data/failed
    ports:
      - "8001:8001"
    command: ["uvicorn", "bulk-service.src.app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload", "--reload-dir", "/app"]
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-True}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - SALESFORCE_CLIENT_ID=${SALESFORCE_CLIENT_ID}
      - SALESFORCE_CLIENT_SECRET=${SALESFORCE_CLIENT_SECRET}
      - SALESFORCE_USERNAME=${SALESFORCE_USERNAME}
      - SALESFORCE_PASSWORD=${SALESFORCE_PASSWORD}
      - SALESFORCE_TOKEN_URL=${SALESFORCE_TOKEN_URL}
      - DATA_PATH_INPUT=/app/data/input
      - DATA_PATH_OUTPUT=/app/data/output
      - DATA_PATH_FAILED=/app/data/failed

# To run:
# 1. Make sure you have a .env file with Salesforce credentials.
# 2. Create local data directories: mkdir -p local_data/input local_data/output local_data/failed
# 3. Run: docker-compose up --build
