apiVersion: apps/v1
kind: Deployment
metadata:
  name: record-service-deployment
  labels:
    app: record-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: record-service
  template:
    metadata:
      labels:
        app: record-service
    spec:
      containers:
        - name: record-service-container
          image: your-docker-registry/record-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: sfdc-api-config
            - secretRef:
                name: sfdc-api-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulk-service-deployment
  labels:
    app: bulk-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulk-service
  template:
    metadata:
      labels:
        app: bulk-service
    spec:
      containers:
        - name: bulk-service-container
          image: your-docker-registry/bulk-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: sfdc-api-config
            - secretRef:
                name: sfdc-api-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: sfdc-api-data-volume
              mountPath: /mnt/data
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 45
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: sfdc-api-data-volume
          persistentVolumeClaim:
            claimName: sfdc-api-pvc-data
