apiVersion: v1
kind: Service
metadata:
  name: record-service
  labels:
    app: record-service
spec:
  type: ClusterIP
  selector:
    app: record-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http-record
---
apiVersion: v1
kind: Service
metadata:
  name: bulk-service
  labels:
    app: bulk-service
spec:
  type: ClusterIP
  selector:
    app: bulk-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: http-bulk
